#!/bin/bash
##########################
#####set variable#########
##########################
cd ~/src/;
tr=$(expr $(date +%M) - $(date -d $(jshon -e 0 -e dateString -u < ~/src/current.json) +%M););
lr=$(jshon -e 0 -e device < ~/src/current.json | cut -c 2) 
direction=$(jshon -e 0 -e direction < ~/src/current.json)
#####################################
########fix bug in time##############
#####################################
#####  if in the last 5 mins of the hour itll return a negative number cuz i didnt account for the hour change , thats what this does
if [ $tr \< 0 ]; then
 tr=$(expr 60 + $tr)
fi
######################################
#######end bug fix ###################
######################################


if [ "$lr" = "x" ]; then 
fr=$(jshon -e 0 -e sgv < ~/src/current.json); 
fi
if [ "$lr" != "x" ]; 
then 
fr=$(jshon -e 0 -e mbg < ~/src/current.json); 
fi


lr2=$(jshon -e 1 -e device < ~/src/current.json | cut -c 2) 
if [ "$lr2" = "x" ]; then 
sr=$(jshon -e 1 -e sgv < ~/src/current.json); 
fi
if [ "$lr2" != "x" ]; 
then 
sr=$(jshon -e 1 -e mbg < current.json); 
fi

delta=$(expr $fr - $sr)" || "$direction
##############################
##############################
####refresh if needed#########
##############################
##############################

if [ "$tr" != "0" ]; 
then 
if [ "$tr" != "1" ]; 
then 
if [ "$tr" != "2" ]; 
then 
if [ "$tr" != "3" ]; 
then 
if [ "$tr" != "4" ]; 
then 
rm -rf ~/src/current*;
wget https://<username>.herokuapp.com/api/v1/entries.json -qO ~/src/current.json;
fi
fi
fi
fi
fi
###################################
########     main   ###############
###################################
while getopts v:d:h:r:t:q option
do
case "${option}"
in
v) echo $fr;;
d) echo "Delta: "$delta;;
h) echo "-r for time recieved";echo "-v for blood sugar ";echo "-d for delta";echo "-t minutes sine last record";;
r) date -d $(jshon -e 0 -e dateString -u < /home/nathan/src/current.json) +%I:%M;;
t) echo $tr;;
esac
done


##############################
########### cleanup ##########
##############################
rm -rf ./wget*
